Chapter5 dev branch
AnalystsUncertaintyToolkit/uncertainty_toolkit_govuk pull request #20
Opened 2023-11-01 16:28 UTC by beccawedge

Addresses issue #11 

Copied over the content for Chapter 5.

I have changed some of the wording for the headers so they make sense, compared to the left hand column of previous website, and added different header levels for section 5.1 to make it flow better.

I've introduced accordions for 5.2, as this seemed neater than having a massive page or splitting into different sections, but let me know your opinions on this.

2023-11-30 14:26 UTC, zslade commented on content/understanding_and_measuring_uncertainty/Quantifying_uncertainty.md
> +We have highlighted ways to think about the uncertainty coming from specific sources. We now bring this together into approaches that can be applied to understand the size and distribution of these u
I wonder whether it would be better to combine this paragraph with the introductory paragraph on the `_index.md` page as it seems to be making broader points than just about this subsectiom

2023-11-30 14:26 UTC, zslade commented on content/understanding_and_measuring_uncertainty/Quantifying_uncertainty.md
> +In addition, the following approaches can be useful in understanding the size and distribution of the uncertainties in your analytical inputs.
And then, if you agree with the above comment, remove "In addition" here

2023-11-30 14:56 UTC, zslade commented on content/understanding_and_measuring_uncertainty/common_techniques.md
> +[MoJ prison population forecasting](https://analystsuncertaintytoolkit.github.io/UncertaintyWeb/case_studies.html#estimating_uncertainty_in_prison_population_projections)
I think the link reference in the new toolkit is probably going to change anyway as we amalgamate the resources chapters but for now probably better to at least link to the case studies chapter, so change link to:
`[MoJ prison population forecasting]({{< ref "/case_studies" >}})`

2023-11-30 16:46 UTC, zslade requested changes
Nice job Becca! The way you've split up the sections with headers is really clear and I think introducing the accordion works really well (I can't remember the accessibility guidance on accordion menus but I'd vote for keeping it this way for now and wait to see what comes back from the accessibility audit)

I've made a few minor comments to address and committed a change just renaming a markdown file

2024-01-04 12:04 UTC, beccawedge commented on content/understanding_and_measuring_uncertainty/Quantifying_uncertainty.md
> +We have highlighted ways to think about the uncertainty coming from specific sources. We now bring this together into approaches that can be applied to understand the size and distribution of these u
I think it fits better here, as it is specifically about quantifying uncertainty. Moving it to _index doesn't flow as nicely

2024-01-16 11:51 UTC, zslade approved these changes

2024-01-16 11:52 UTC, zslade commented
Thanks Becca! Ready to merge 🚀

2024-05-21 08:33 UTC, merged

2024-05-21 08:56 UTC, zslade commented
[heart]         Slade, Zoe reacted to your message:
________________________________
From: ghpickering ***@***.***>
Sent: Tuesday, May 21, 2024 8:34:08 AM
To: AnalystsUncertaintyToolkit/uncertainty_toolkit_govuk ***@***.***>
Cc: Slade, Zoe ***@***.***>; Assign ***@***.***>
Subject: Re: [AnalystsUncertaintyToolkit/uncertainty_toolkit_govuk] Chapter5 dev branch (PR #20)


Merged #20<https://github.com/AnalystsUncertaintyToolkit/uncertainty_toolkit_govuk/pull/20> into dev.

—
Reply to this email directly, view it on GitHub<https://github.com/AnalystsUncertaintyToolkit/uncertainty_toolkit_govuk/pull/20#event-12876230132>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEYWAO5WZB7A4MDBZPK3RNLZDMBIBAVCNFSM6AAAAAA6ZRNZ3SVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSHA3TMMRTGAYTGMQ>.
You are receiving this because you were assigned.Message ID: ***@***.***>

________________________________
This e-mail and any attachments is intended only for the attention of the addressee(s). Its unauthorised use, disclosure, storage or copying is not permitted. If you are not the intended recipient, please destroy all copies and inform the sender by return e-mail. Internet e-mail is not a secure medium. Any reply to this message could be intercepted and read by someone else. Please bear that in mind when deciding whether to send material in response to this message by e-mail. This e-mail (whether you are the sender or the recipient) may be monitored, recorded and retained by the Ministry of Justice. Monitoring / blocking software may be used, and e-mail content may be read at any time. You have a responsibility to ensure laws are not broken when composing or forwarding e-mails and their contents.